// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeW4d_NgSKr2zZKzPiR8ahnGEUZzbGxMg',
    appId: '1:661685076637:web:482a642e8ca85eefdf0a74',
    messagingSenderId: '661685076637',
    projectId: 'psysio-25b98',
    authDomain: 'psysio-25b98.firebaseapp.com',
    databaseURL: 'https://psysio-25b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'psysio-25b98.firebasestorage.app',
    measurementId: 'G-8N2Q1MRBH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfgM2aj--X1ozeb99jJ45B6UhPe5E0eGs',
    appId: '1:661685076637:android:134fb1f7b34ad936df0a74',
    messagingSenderId: '661685076637',
    projectId: 'psysio-25b98',
    databaseURL: 'https://psysio-25b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'psysio-25b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrFQPLA_iZCShBvCfwVxyBEUKQ8J6T034',
    appId: '1:661685076637:ios:70f4e6556f2a5aaddf0a74',
    messagingSenderId: '661685076637',
    projectId: 'psysio-25b98',
    databaseURL: 'https://psysio-25b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'psysio-25b98.firebasestorage.app',
    iosClientId: '661685076637-m3qk55tjje5ps66takle9qca7esd3a0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheldule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrFQPLA_iZCShBvCfwVxyBEUKQ8J6T034',
    appId: '1:661685076637:ios:70f4e6556f2a5aaddf0a74',
    messagingSenderId: '661685076637',
    projectId: 'psysio-25b98',
    databaseURL: 'https://psysio-25b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'psysio-25b98.firebasestorage.app',
    iosClientId: '661685076637-m3qk55tjje5ps66takle9qca7esd3a0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheldule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFid8aCw-PXjpe1xObwfmtbpGgqtNfhto',
    appId: '1:661685076637:web:6aca9fd88e7982bbdf0a74',
    messagingSenderId: '661685076637',
    projectId: 'psysio-25b98',
    authDomain: 'psysio-25b98.firebaseapp.com',
    databaseURL: 'https://psysio-25b98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'psysio-25b98.firebasestorage.app',
    measurementId: 'G-4VGB9451QQ',
  );
}
